### ISSUE TITLE
Error: error in tree: too many species in tree.

### ISSUE THREAD

**Issue by YDD99** [sabifo4/mammals_dating#57]
singularity  exec "/home/xly/soft/PhyloTools.sif" mcmctree mcmctree.ctl > run.log

Error: error in tree: too many species in tree.

just 77 species

**Comment by sabifo4** [comment]
Hi there!

This is not the correct repository to report this issue. You seem to have problems with running `MCMCtree` due to having the wrong number of taxa. There may be a mismatch between the taxa you have in your alignment and the taxa you have in your tree. As you can see, this problem has nothing to do with the content of this repository.

Please report `MCMCtree` problems in the PAML discussion group: https://groups.google.com/g/pamlsoftware

This issue is now closed.
